### ISSUE TITLE
Introduce a `begin` / `do` / `progn` form

### ISSUE THREAD

**Issue by fitzgen** [cfallin/isle#7]
When we are emitting multiple instructions to already-chosen registers, we end up doing a bunch of stuff that could have some sugar:

```lisp
;; `()` in Rust.
(type Unit (primitive Unit))

;; ...

(rule (lower (and (iconst (unwrap_u64_from_imm64 x))
                  (instruction_type $i128)))
      (let (_ Unit (emit (imm (OperandSize.Size64) x (get_output_reg_0))))
        (xor (OperandSize.Size64)
             (RegMemImm.Reg (writable_reg_to_reg (output_reg_1)))
             (output_reg_1))))
```

This would be nicer with `(do ...)` instead of `(let (_ Unit ...) ...)`:

```lisp
(rule (lower (and (iconst (unwrap_u64_from_imm64 x))
                  (instruction_type $i128)))
      (do (emit (imm (OperandSize.Size64) x (get_output_reg_0)))
          (xor (OperandSize.Size64)
               (RegMemImm.Reg (writable_reg_to_reg (output_reg_1)))
               (output_reg_1))))
```

**Comment by cfallin** [comment]
Hmm, it seems this is drifting a bit back into imperative-land, which is actually really interesting to me because earlier forms of ISLE were basically imperative and side-effect-driven (inspired by Prolog). Nothing wrong with that if it's what makes sense; but I do want to think carefully about this... in particular:

- Do we need an `emit` constructor with a side-effect of emitting a value? Why not use an `(imm ...)` form whose constructor implicitly emits?
- The `(get_output_reg_0)` constructor I think is getting at what I had mentioned a few weeks ago in our call -- there will need to be a way to "fill in later" the output reg if we have a pure value-based design. Basically the instructions today list the output regs alongside all the others; they're arguments from the PoV of the constructor; instead we need the instruction to, semantically, emit into some separately-provided reg, which could come from e.g. a `.with_output(...)` updater on the `MachInst` or something like that.
- I realize the above two points are slightly in conflict; when `(imm ...)` is constructed we don't yet know where its result should go so we *can't* emit it yet. One idea: constructors take the original SSA values they're meant to be equivalent to, and use the pre-assigned output reg for that SSA value (they're pre-assigned because we scan backward so we'll already have used this reg to consume the value), or `None` in which case a temp is used? That's a little ugly though.

Anyway, it's interesting to me that you're sort of retracing the design steps I had that originally led me to the more imperative worldview; perhaps we can still get out of it :-)

**Comment by fitzgen** [comment]
It would be nice if `MachInst` was defined like

```rust
pub enum MachInst {
    AluRmiR {
        size: OperandSize, // 4 or 8
        op: AluRmiROpcode,
        src_a: RegMemImm,
        src_b: Reg,
        dst: Writable<Reg>,
    },
    // ...
}
```

Instead of eagerly going into 2-operand form where `dst` is both read and written to. But then when encoding instructions, we would assert that `src_b == dst` or `src_a == dst` depending on the Mod R/M bits we want to emit. This would align with our plans to move to regalloc2 and input SSA into the register allocator, and would also let us use a more value-based approach in ISLE.

**Comment by fitzgen** [comment]
Lowering `iconst.i128` is an interesting one, because it lowers to two instructions, neither of which reference the other one. So we *have* to have a side-effecting emit of some sort, unless we change the top-level `lower` function to return a list of instructions.
